FROM node:16


WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install && \
    npm run build && \
    npm install -g serve && \
    rm -rf node_modules src && \
    npm cache clean --force && \
    useradd -m appuser && \
    chown appuser /usr/src/app

USER appuser

EXPOSE 5000

CMD ["serve", "-s", "build", "-l", "5000"]